### ISSUE TITLE
Unable to create new chat from Web client on the chat window page

### ISSUE THREAD

**Issue by DavidChavarro** [Aletheianomous-AI/Chatbot-SP15#8]
I am not able to create a new conversation when clicking the `New Chat` on the chat window page. When looking at the browser console logs, a cyclical object error is thrown. I have added a `console.log()` statement inside the `handleNewChat` function at the `ChatHistory.js` file, and it returns a dictionary representing a React component object. I might recommend you to investigate on its causes.

**Comment by aimiisme** [comment]
Hi David, It would be great if you could send me a video of you running the web app + frontend + backend. It'll help me see what's working and what isn't and know what I am supposed to do. Without access to the real-time database and backend, I'm working blindly with no solution and this is not a good practice.

**Comment by DavidChavarro** [comment]
@aimiisme I will have the video recorded and send you a YouTube link that describes how the entire system works, and what issue I am having with adding the chat.

**Comment by DavidChavarro** [comment]
@aimiisme I have uploaded the video to YouTube. Since this Issue is public, I have sent the video link to your KSU Outlook mailbox. So please check your mail for the link. I hope this video helps.

**Comment by aimiisme** [comment]
Implemented the New Chat feature under the commit [5683650](https://github.com/Aletheianomous-AI/Chatbot-SP15/commit/56836504c2689477500f94e62c48a18b50f5f8d2)

**Comment by DavidChavarro** [comment]
Thank you very much Aimi. I will test the feature before I close the issue.

**Comment by DavidChavarro** [comment]
I've tested the feature and the new chat function works.
